[package]
name = "aw3d30"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
log = "0.4.26"
serde = { version = "1.0.218", features = ["derive"] }
thiserror = "2.0.12"
tiff = "0.9.1"
ureq = "2.12.1"
zip = "2.2.3"
zstd = "0.13.3"

