from .steps import StepsGenerator
from .crossing import CrossingGenerator
from .protected_area import ProtectedAreaGenerator
from .platform import PlatformGenerator
from .stop import StopGenerator
from .border import BorderGenerator
from .boundary import BoundaryGenerator
from .water_way import WaterWayGenerator
from .track import TrackGenerator
from .aerial_way import AerialWayGenerator
from .service_road import ServiceRoadGenerator
from .road import RoadGenerator
from .railway import RailWayGenerator
from .parking import ParkingGenerator
from .grave_yard import GraveYardGenerator
from .shelter import ShelterGenerator
from .recycling import RecyclingGenerator
from .fuel import FuelGenerator
from .post_box import PostBoxGenerator
from .pub import PubGenerator
from .fountain import FountainGenerator
from .atm import ATMGenerator
from .bank import BankGenerator
from .social_facility import SocialFacilityGenerator
from .clock import ClockGenerator
from .bicycle_parking import BicycleParkingGenerator
from .board import BoardGenerator
from .shop import ShopGenerator
from .craft import CraftGenerator
from .office import OfficeGenerator
from .castle import CastleGenerator
from .transformer import TransformerGenerator
from .power_line import PowerLineGenerator
from .power_substation import PowerSubstationGenerator
from .power_generator import PowerGeneratorGenerator
from .pole import PoleGenerator
from .power import PowerGenerator
from .area import AreaGenerator
from .tower import TowerGenerator
from .power_plant import PowerPlantGenerator
from .healthcare import HealthCareGenerator
from .building import BuildingGenerator
from .tourism import TourismGenerator
from .surveillance import SurveillanceGenerator
from .cafe import CafeGenerator
from .amenity import AmenityGenerator
from .checkpoint import CheckpointGenerator
from .tree import TreeGenerator
from .water_area import WaterAreaGenerator
from .natural import NaturalGenerator
from .sport import SportGenerator
from .bunker import BunkerGenerator
from .place import PlaceGenerator
from .garden import GardenGenerator
from .land import LandGenerator
from .golfcourse import GolfCourseGenerator
from .playground import PlaygroundGenerator
from .leisure import LeisureGenerator
from .barrier import BarrierGenerator
from .memorial import MemorialGenerator
from .historic import HistoricGenerator
from .traffic_sign import TrafficSignGenerator
from .addressable import AddressableGenerator
from .no_exit import NoExitGenerator
from .fire_hydrant import FireHydrantGenerator
from .entrance import EntranceGenerator
from .bench import BenchGenerator
from .traffic_calming import TrafficCalmingGenerator
from .ford import FordGenerator
from .school_thing import SchoolThingGenerator
from .notice import NoticeGenerator
from .route import RouteGenerator
from .restriction import RestrictionGenerator
from .site import SiteGenerator
from .collection import CollectionGenerator
from .man_made import ManMadeGenerator
from .advertising import AdvertisingGenerator
from .disused import DisusedGenerator
from .demolished_building import DemolishedBuildingGenerator
from .construction import ConstructionGenerator
from .abandoned import AbandonedGenerator
from .fee import FeeGenerator
from .piste import PisteGenerator
from .annotated import AnnotatedGenerator
from .named import NamedGenerator
from .commented import CommentedGenerator
from .elevated import ElevatedGenerator
from .accessible import AccessibleGenerator
from .building_part import BuildingPartGenerator
from .no_op import NoOpGenerator