"""newest_osm_object_timestamp

Revision ID: c1ffd3316700
Revises: 0215b03e5e8f
Create Date: 2018-03-10 22:56:07.833829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ffd3316700'
down_revision = '0215b03e5e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area', sa.Column('newest_osm_object_timestamp', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('area', 'newest_osm_object_timestamp')
    # ### end Alembic commands ###
