[package]
name = "oesc"
version = "0.1.0"
authors = ["Lukáš Tyrychtr <lukastyrychtr@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
osm_api = {path="../osm_api"}
osm_db = {path="../osm_db"}
redis_api = {path = "../redis_api"}
server={path="../server"}
anyhow = "1.0.86"
dotenvy = "0.15.7"
url = "2.5.2"
ureq = { version = "2.10.0", default-features = false, features = ["tls", "json"] }
serde = { version = "1.0.204", features = ["derive"] }
clap = { version = "4.5.13", features = ["derive"] }

[features]
