[package]
name = "oesc"
version = "0.1.0"
authors = ["Lukáš Tyrychtr <lukastyrychtr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
osm_api = {path="../osm_api"}
osm_db = {path="../osm_db"}
redis_api = {path = "../redis_api"}
server={path="../server"}
anyhow = "1.0.66"
dotenvy = "0.15.6"
diesel = { version = "2.0.2", features = ["sqlite", "chrono"] }
url = "2.3.1"
ureq = { version = "2.5.0", default-features = false, features = ["tls", "json"] }
serde = { version = "1.0.150", features = ["derive"] }
clap = { version = "4.0.29", features = ["derive"] }

[features]
