[package]
name = "oesc"
version = "0.1.0"
authors = ["Lukáš Tyrychtr <lukastyrychtr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
osm_db = {path="../osm_db"}
redis_api = {path = "../redis_api"}
server={path="../server"}
structopt="*"
anyhow = "*"
dotenv = "*"
diesel = {version = "*", features = ["sqlite", "chrono"]}
url = "*"
ureq = {version="*", default_features=false, features=["tls", "json"]}
serde = {version="*", features=["derive"]}
