[package]
name = "oesc"
version = "0.1.0"
authors = ["Lukáš Tyrychtr <lukastyrychtr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
osm_db = {path="../osm_db"}
redis_api = {path = "../redis_api"}
server={path="../server"}
structopt= "0.3.25"
anyhow = "1.0.50"
dotenv = "0.15.0"
diesel = { version = "1.4.8", features = ["sqlite", "chrono"] }
url = "2.2.2"
ureq = { version = "2.3.1", default_features = false, features = ["tls", "json"] }
serde = { version = "1.0.130", features = ["derive"] }
