[package]
name = "oesc"
version = "0.1.0"
authors = ["Lukáš Tyrychtr <lukastyrychtr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
osm_api = {path="../osm_api"}
osm_db = {path="../osm_db"}
redis_api = {path = "../redis_api"}
server={path="../server"}
anyhow = "1.0.57"
dotenv = "0.15.0"
diesel = { version = "1.4.8", features = ["sqlite", "chrono"] }
url = "2.2.2"
ureq = { version = "2.4.0", default_features = false, features = ["tls", "json"] }
serde = { version = "1.0.137", features = ["derive"] }
clap = { version = "3.2.4", features = ["derive"] }

[features]
