from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()
from .idx_entities_geometry import IdxEntitiesGeometry
from .entity import Entity
from .address import Address
from .named import Named
from .commented import Commented
from .addressable import Addressable
from .elevated import Elevated
from .road import Road
from .rail_way import RailWay
from .parking import Parking
from .land import Land
from .building import Building
from .castle import Castle
#from .address import Address
from .track import Track
from .service_road import ServiceRoad
from .shop import Shop
from .steps import Steps
from .area import Area
from .graveyard import Graveyard
from .water_area import WaterArea
from .leisure import Leisure
from .water_way import WaterWay
from .power_plant import PowerPlant
from .boundary import Boundary
from .power_line import PowerLine
from .protected_area import ProtectedArea
from .barrier import Barrier
from .platform import Platform
from .natural import Natural
from .shelter import Shelter
from .man_made import ManMade
from .aerial_way import AerialWay
from .recycling import Recycling
from .tourism import Tourism
from .stop import Stop
from .fuel import Fuel
from .crossing import Crossing
from .post_box import PostBox
from .pub import Pub
from .fountain import Fountain
from .theatre import Theatre
from .amenity import Amenity
from .bank import Bank
from .power import Power
from .place import Place
from .atm import ATM
from .historic import Historic
from .power_generator import PowerGenerator
from .traffic_sign import TrafficSign
from .tree import Tree
from .no_exit import NoExit
from .entrance import Entrance
from .bench import Bench
from .traffic_calming import TrafficCalming
from .social_facility import SocialFacility
from .office import Office
from .sport import Sport
from .clock import Clock
from .school_thing import SchoolThing
from .annotated import Annotated
from .notice import Notice
from .bicycle_parking import BicycleParking
from .accessible import Accessible
from .memorial import Memorial
from .craft import Craft
from .board import Board
from .fire_hydrant import FireHydrant
from .bunker import Bunker
from .checkpoint import Checkpoint
from .pole import Pole
from .advertising import Advertising
from .power_substation import PowerSubstation
from .disused import Disused
from .demolished_building import DemolishedBuilding
from .construction import Construction
from .abandoned import Abandoned
from .fee import Fee
from .tower import Tower
from .piste import Piste
from .garden import Garden
from .building_part import BuildingPart
from .route import Route
from .border import Border
from .site import Site
from .collection import Collection
from .restriction import Restriction
from .transformer import Transformer
from .health_care import HealthCare
from .golf_course import GolfCourse
from .playground import Playground
from .surveillance import Surveillance
from .cafe import Cafe
from .associated_street import AssociatedStreet
from .bridge import Bridge
from .rf import RF
from .street import Street
from .level import Level
from .public_transport import PublicTransport
from .enforcement import Enforcement